# -*- coding: utf-8 -*-
"""Pokémon Battle System Project 2.9.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQRIYjgL1fTF7F3DQzCQ4Br3NfSf96ag
"""

# Define your Pokemon here
Bulbasaur = {'hp': 100, 'acc': 100}
Pikachu = {'hp': 100, 'acc': 100}
def game():
    def print_stats():
      print("Bulbasaur" + "\nhp " + str(Bulbasaur['hp']) + " acc " + str(Bulbasaur['acc']))
      print("Pikachu" + "\nhp " + str(Pikachu['hp']) + " acc " + str(Pikachu['acc']))

    while True:
        print("It's a Bulbasaur <<press enter>>")
        user_input = input('')
        if user_input == '':
            while True:
                print("What do you want to do?")
                print("1. Battle")
                print("2. Run away")
                ans = input('<<input 1. or 2.>> ')
                if ans == '1':   #If player selects ‘1. Battle’ then we choose Pikachu and continue the game
                    while True:
                        print("Pikachu I choose you <<press enter>>")
                        user_input = input()
                        if user_input == '':
                            print_stats()  # After Each turn, we display the hitpoints and accuracy for each Pokémon
                            print("<<press enter>>")
                            user_input = input('')
                            if user_input != '':
                                print("Please just press 'Enter' without typing anything.")
                            else:
                                import random
                                move = random.choice(['Tackle', 'Sand Attack']) #Bulbasaur (opponent) strikes first, and attacks with either Tackle or Sand Attack
                                print("Bulbasaur uses " + move)
                                user_input = input("<<press enter>>")
                                if user_input != '':
                                    print("Please just press 'Enter' without typing anything.")
                                else:
                                  if random.randint(1, 100) <= Bulbasaur['acc']: # The probability of landing a Tackle or Sand attack is accuracy %.
                                      if move == 'Tackle':
                                          print("Bam!")
                                          Pikachu['hp'] -= 10  #Tackle deals 10 damage
                                          if Pikachu['hp'] <= 0:  #If Pikachu loses all hp 'Pikachu fainted'
                                              print("Pikachu fainted")
                                              break
                                      if move == 'Sand Attack':
                                          print("Swoosh!")
                                          Pikachu['acc'] -= 10  #Sand Attack reduces accuracy by 10
                                  else:
                                      print("But it missed!")
                                  print_stats()
                                  print("<<press enter>>")
                                  user_input = input('')
                                  if user_input != '':
                                      print("Please just press 'Enter' without typing anything.")
                                  else:
                                      def player_turn():
                                        print("Then it is your turn, and you must select between Tackle, Sand Attack, and Throw Pokeball")
                                        print("What to do?")
                                        print("1. Tackle")
                                        print("2. Sand Attack")
                                        print("3. Throw Pokeball")
                                        choice = input("<<enter 1, 2, or 3>>\n")
                                        action = 'hit' if random.randint(1, 100) <= Pikachu['acc'] else 'miss'

                                        if choice == "1":
                                            print("Pikachu uses Tackle")
                                            input("<<press enter>>")
                                            if action == 'hit':
                                              print("Bam!")
                                              Bulbasaur['hp'] -= 10  # Reduce Bulbasaur's hp by 10
                                              if Bulbasaur['hp'] <= 0:
                                                print("Bulbasaur fainted")

                                            else:
                                              print("But it missed!")
                                            print_stats()
                                            return "Tackle"
                                        elif choice == "2":
                                            print("Pikachu uses Sand Attack")
                                            input("<<press enter>>")
                                            if action == 'hit':
                                              print("Swoosh!")
                                              Bulbasaur['acc'] -= 10  # Reduce Bulbasaur's accuracy by 10
                                            else:
                                              print("But it missed!")
                                            print_stats()
                                            return "Sand Attack"
                                        elif choice == "3":
                                            print("You threw a Pokeball")
                                            input("<<press enter>>")
                                            # Calculate the chance of catching Bulbasaur
                                            catch_chance = 100 - Bulbasaur['hp']
                                            if random.randint(1, 100) <= catch_chance:
                                              print("You caught a Bulbasaur!")
                                            else:
                                              print("But it broke free!")
                                            print_stats()
                                            return "Throw Pokeball"
                                        else:
                                            print("Invalid choice. Try again.")
                                            return player_turn()
                                    # After Bulbasaur attacks, it's the player's turn
                                      pikachu_move = player_turn()
                                      break

                                      while user_input != '':
                                          print("Please just press 'Enter' without typing anything.")
                                          user_input = input("<<press enter>>")
                        else:
                            print("Please just press 'Enter' without typing anything.")
                elif ans == '2': #If player selects ‘2. Run Away’ then program terminates
                    print("Goodbye!")
                    return
                else:
                    print("I'm sorry please enter 1 or 2.")
        else:
            print("Please just press 'Enter' without typing anything.")
game() #Name: Sushmita Persaud